[build]
buildCommand = "cd ../.. && pnpm install --frozen-lockfile && pnpm turbo run build --filter=api"
builder = "NIXPACKS"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 120
restartPolicyMaxRetries = 10
restartPolicyType = "ON_FAILURE"
startCommand = "node dist/index.cjs"
